### PR TITLE
Added hyperlinks to communication platforms

### PR DESCRIPTION
**Pull request by manula2004**
##### ISSUE TYPE

 
 - Docs Pull Request

##### SUMMARY

I added proper hyperlinks to slack, mattermost and microsoft teams

### CODE REVIEW

**Review by bhavin192 — APPROVED** [review]

**Comment by chetanpdeshmukh** [comment]
Hello @manula2004 ,
Thanks again for the PR!

Thank you for contributing to BotKube. Could you please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSdULT22oZlpHPMXKVEtV4fZ6R8vdGDC2iFvMhoG6IhZkK1SFA/viewform?usp=sf_link), so we can send the well deserved awesome swags :slightly_smiling_face:

Team BotKube

**Comment by manula2004** [comment]
@chetanpdeshmukh  Hi, can you please tell me what you mean by pin code in the form?
Is it supposed to be the zip code?

**Comment by chetanpdeshmukh** [comment]
> @chetanpdeshmukh Hi, can you please tell me what you mean by pin code in the form?
> Is it supposed to be the zip code?

Yes, it is zip code

**Comment by manula2004** [comment]
@chetanpdeshmukh  Hello again. Can I please have a status update on the t-shirt? I haven't recieved the t-shirt yet, So i want know when it might arrive here. It would really mean a lot

Thanks

**Pull request merged**
