### PR TITLE
fix(charts): correct indentation for rbac rules

### LINKED ISSUE #325: [BUG] Helm Chart clusterrole invalid if PSP and rbac are both enabled
**Describe the bug**
If both RBAC and PSP are enabled the two rules added to the clusterrole are not indented the same.
https://github.com/infracloudio/botkube/blob/develop/helm/botkube/templates/clusterrole.yaml#L11

**To Reproduce**
Install chart (or template) with both rbac and psp enabled.

**Expected behavior**
Cluster role is set correctly.

**Screenshots**

```yaml
---
# Source: botkube/templates/clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: botkube-clusterrole
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.10.0
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
rules:
    - apiGroups:
      - '*'
      resources:
      - '*'
      verbs:
      - get
      - watch
      - list
  - apiGroups: ["extensions"]
    resourceNames: ["botkube-psp"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]

```

**Additional context**

### PR DESCRIPTION
**Pull request by aslafy-z**
##### ISSUE TYPE

 - Bug fix Pull Request

##### SUMMARY

Correctly indent RBAC rules. It was previously throwing an error when enabling both psp and rbac at the value level. 

Fixes #325

### CODE REVIEW

**Comment by PrasadG193** [comment]
Hey @aslafy-z, 
Thanks for the PR. Please let us know when the PR is ready for review

**Comment by gauravgahlot** [comment]
@aslafy-z Please rebase your branch once ready.

**Comment by PrasadG193** [comment]
@aslafy-z can you please provide an output of 
`helm install --name botkube --namespace botkube --set rbac.create=true,podSecurityPolicy.enabled=true ./helm/botkube --dry-run --debug`?

**Review by PrasadG193 — APPROVED** [review]

**Comment by chetanpdeshmukh** [comment]
Hello @aslafy-z 
Thanks again for the PR!

Thank you for contributing to BotKube. Could you please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSdULT22oZlpHPMXKVEtV4fZ6R8vdGDC2iFvMhoG6IhZkK1SFA/viewform?usp=sf_link), so we can send the well deserved awesome swags :slightly_smiling_face:

Team BotKube

**Pull request merged**
