### PR TITLE
[unit test] Unit tests for config package

### PR DESCRIPTION
**Pull request by imazik**
This PR contains unit tests for config package.

### CODE REVIEW

**Comment by PrasadG193** [comment]
Thanks @imazik for the PR :) 
We should integrate the execution of tests in travis CI.

**Comment by imazik** [comment]
Yes, done in #104

**Comment by PrasadG193** [comment]
Should we also check if config.New() unmarshal config correctly and returns correct Config struct as a part of this?

**Comment by imazik** [comment]
> Should we also check if config.New() unmarshal config correctly and returns correct Config struct as a part of this?

Yes will update this.

**Comment by ssudake21** [comment]
@imazik  Are you still actively working on this PR ? You may need to rebase as well.

**Comment by ssudake21** [comment]
@PrasadG193 Please see if any tests from this PR can be pulled along new ones you are adding.

**Comment by sanketsudake** [comment]
Closing this PR as no updates from contributor. Please re-raise fresh PR for any further updates/changes.

**Pull request closed without merging**
