### PR TITLE
[unit test] Enable Unit test and add target in Makefile

### LINKED ISSUE #144: Unit-Test code in Travis
**Is your feature request related to a problem? Please describe.**
It is essential to Unit-Test the code during each build to ensure that, the code changes made don't break any existing features. 

**Describe the solution you'd like**
- add `make test` subcommand to Unit-test locally 
- add `make test` to .travis.yml to Unit-Test code in Travis build

**Describe alternatives you've considered**
Unit-Test code manually using `go test ./...` command before each git push

### PR DESCRIPTION
**Pull request by aananthraj**
##### ISSUE TYPE

 - Feature Pull Request

##### SUMMARY

This PR
- Adds make target to run unit tests
- Enable unit test check in travis

Signed-off-by: Shovan Maity <shovan.cse91@gmail.com>

Patched 
- Rebased `imazik:enable-unit-test` onto `infracloudio:develop` 
- adds `unit-test` to `make release`

Signed-off-by: Aananth K <aananthraj1995@gmail.com>

Fixes #144

### CODE REVIEW

**Comment by PrasadG193** [comment]
Should we also run unit tests when we `make git-tag`?

**Comment by aananthraj** [comment]
> Should we also run unit tests when we `make git-tag`?

during a release.?
Do we have any seperate use case for git-tag excluding release.?
https://github.com/infracloudio/botkube/blob/598802e91cc4c638aa9e3bd741e494f9e1d8143b/Makefile#L9

**Comment by PrasadG193** [comment]
Nope, we can add it in `release` also.

**Comment by aananthraj** [comment]
added `unit-test` to `make release`

**Pull request merged**
