### PR TITLE
[Feature] Add the ability to specify a kubeconfig and disable service account token mounting in helm chart

### PR DESCRIPTION
**Pull request by sudermanjr**
##### ISSUE TYPE

 - Feature Pull Request

##### SUMMARY
This provides the ability to directly specify a kubeconfig for botkube to use when installing via helm. In addition, it adds a value that will disable service account token mounting. This provides the ability to run botkube against other clusters that it is not currently running in.

### CODE REVIEW

**Comment by sudermanjr** [comment]
@bhavin192 any thoughts on this PR?

**Comment by PrasadG193** [comment]
@sudermanjr could you please attach `--dry-run --debug` output of helm install with the options you proposed set?

**Comment by sudermanjr** [comment]
```
helm install --debug --dry-run  botkube ./ --set kubeconfig.enabled=true --set kubeconfig.existingSecret=kubeconfig-supersecret | tee /tmp/output.txt

cat output.txt

NAME: botkube
LAST DEPLOYED: Wed Nov 24 10:51:31 2021
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
kubeconfig:
  enabled: true
  existingSecret: kubeconfig-supersecret

COMPUTED VALUES:
affinity: {}
automountServiceAccountToken: true
communications:
  discord:
    botid: DISCORD_BOT_ID
    channel: DISCORD_CHANNEL_ID
    enabled: false
    notiftype: short
    token: DISCORD_TOKEN
  elasticsearch:
    awsSigning:
      awsRegion: us-east-1
      enabled: false
      roleArn: ""
    enabled: false
    index:
      name: botkube
      replicas: 0
      shards: 1
      type: botkube-event
    password: ELASTICSEARCH_PASSWORD
    server: ELASTICSEARCH_ADDRESS
    skipTLSVerify: false
    username: ELASTICSEARCH_USERNAME
  existingSecretName: ""
  mattermost:
    botName: BotKube
    channel: MATTERMOST_CHANNEL
    enabled: false
    notiftype: short
    team: MATTERMOST_TEAM
    token: MATTERMOST_TOKEN
    url: MATTERMOST_SERVER_URL
  slack:
    channel: SLACK_CHANNEL
    enabled: false
    notiftype: short
    token: SLACK_API_TOKEN
  teams:
    appID: APPLICATION_ID
    appPassword: APPLICATION_PASSWORD
    enabled: false
    notiftype: short
    port: 3978
  webhook:
    enabled: false
    url: WEBHOOK_URL
config:
  recommendations: true
  resources:
  - events:
    - create
    - delete
    - error
    name: v1/pods
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: v1/services
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - update
    - delete
    - error
    name: apps/v1/deployments
    namespaces:
      ignore:
      - null
      include:
      - all
    updateSetting:
      fields:
      - spec.template.spec.containers[*].image
      - status.availableReplicas
      includeDiff: true
  - events:
    - create
    - update
    - delete
    - error
    name: apps/v1/statefulsets
    namespaces:
      ignore:
      - null
      include:
      - all
    updateSetting:
      fields:
      - spec.template.spec.containers[*].image
      - status.readyReplicas
      includeDiff: true
  - events:
    - create
    - delete
    - error
    name: networking.k8s.io/v1beta1/ingresses
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: v1/nodes
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: v1/namespaces
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: v1/persistentvolumes
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: v1/persistentvolumeclaims
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: v1/configmaps
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - update
    - delete
    - error
    name: apps/v1/daemonsets
    namespaces:
      ignore:
      - null
      include:
      - all
    updateSetting:
      fields:
      - spec.template.spec.containers[*].image
      - status.numberReady
      includeDiff: true
  - events:
    - create
    - update
    - delete
    - error
    name: batch/v1/jobs
    namespaces:
      ignore:
      - null
      include:
      - all
    updateSetting:
      fields:
      - spec.template.spec.containers[*].image
      - status.conditions[*].type
      includeDiff: true
  - events:
    - create
    - delete
    - error
    name: rbac.authorization.k8s.io/v1/roles
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: rbac.authorization.k8s.io/v1/rolebindings
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: rbac.authorization.k8s.io/v1/clusterrolebindings
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: rbac.authorization.k8s.io/v1/clusterroles
    namespaces:
      ignore:
      - null
      include:
      - all
  settings:
    clustername: not-configured
    configwatcher: true
    kubectl:
      commands:
        resources:
        - deployments
        - pods
        - namespaces
        - daemonsets
        - statefulsets
        - storageclasses
        - nodes
        verbs:
        - api-resources
        - api-versions
        - cluster-info
        - describe
        - diff
        - explain
        - get
        - logs
        - top
        - auth
      defaultNamespace: default
      enabled: false
      restrictAccess: false
    upgradeNotifier: true
  ssl:
    enabled: false
containerSecurityContext:
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
extraAnnotations: {}
extraEnv: null
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  repository: infracloudio/botkube
  tag: v0.12.3
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  create: false
  host: HOST
  tls:
    enabled: false
    secretName: ""
  urlPath: /
kubeconfig:
  base64Config: ""
  enabled: true
  existingSecret: kubeconfig-supersecret
logLevel: info
nameOverride: ""
nodeSelector: {}
podSecurityPolicy:
  enabled: false
priorityClassName: ""
rbac:
  create: true
  rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - get
    - watch
    - list
replicaCount: 1
resources: {}
securityContext:
  runAsGroup: 101
  runAsUser: 101
service:
  name: metrics
  port: 2112
  targetPort: 2112
serviceAccount:
  annotations: {}
  create: true
serviceMonitor:
  enabled: false
  interval: 10s
  labels: {}
  path: /metrics
  port: metrics
tolerations: []

HOOKS:
MANIFEST:
---
# Source: botkube/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: botkube-sa
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: botkube/templates/communicationsecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: botkube-communication-secret
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
stringData:
  comm_config.yaml: |
    # Communication settings
    communications:
      discord:
        botid: DISCORD_BOT_ID
        channel: DISCORD_CHANNEL_ID
        enabled: false
        notiftype: short
        token: DISCORD_TOKEN
      elasticsearch:
        awsSigning:
          awsRegion: us-east-1
          enabled: false
          roleArn: ""
        enabled: false
        index:
          name: botkube
          replicas: 0
          shards: 1
          type: botkube-event
        password: ELASTICSEARCH_PASSWORD
        server: ELASTICSEARCH_ADDRESS
        skipTLSVerify: false
        username: ELASTICSEARCH_USERNAME
      existingSecretName: ""
      mattermost:
        botName: BotKube
        channel: MATTERMOST_CHANNEL
        enabled: false
        notiftype: short
        team: MATTERMOST_TEAM
        token: MATTERMOST_TOKEN
        url: MATTERMOST_SERVER_URL
      slack:
        channel: SLACK_CHANNEL
        enabled: false
        notiftype: short
        token: SLACK_API_TOKEN
      teams:
        appID: APPLICATION_ID
        appPassword: APPLICATION_PASSWORD
        enabled: false
        notiftype: short
        port: 3978
      webhook:
        enabled: false
        url: WEBHOOK_URL
---
# Source: botkube/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: botkube-configmap
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
data:
  resource_config.yaml: |
    recommendations: true
    resources:
    - events:
      - create
      - delete
      - error
      name: v1/pods
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: v1/services
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - update
      - delete
      - error
      name: apps/v1/deployments
      namespaces:
        ignore:
        - null
        include:
        - all
      updateSetting:
        fields:
        - spec.template.spec.containers[*].image
        - status.availableReplicas
        includeDiff: true
    - events:
      - create
      - update
      - delete
      - error
      name: apps/v1/statefulsets
      namespaces:
        ignore:
        - null
        include:
        - all
      updateSetting:
        fields:
        - spec.template.spec.containers[*].image
        - status.readyReplicas
        includeDiff: true
    - events:
      - create
      - delete
      - error
      name: networking.k8s.io/v1beta1/ingresses
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: v1/nodes
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: v1/namespaces
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: v1/persistentvolumes
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: v1/persistentvolumeclaims
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: v1/configmaps
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - update
      - delete
      - error
      name: apps/v1/daemonsets
      namespaces:
        ignore:
        - null
        include:
        - all
      updateSetting:
        fields:
        - spec.template.spec.containers[*].image
        - status.numberReady
        includeDiff: true
    - events:
      - create
      - update
      - delete
      - error
      name: batch/v1/jobs
      namespaces:
        ignore:
        - null
        include:
        - all
      updateSetting:
        fields:
        - spec.template.spec.containers[*].image
        - status.conditions[*].type
        includeDiff: true
    - events:
      - create
      - delete
      - error
      name: rbac.authorization.k8s.io/v1/roles
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: rbac.authorization.k8s.io/v1/rolebindings
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: rbac.authorization.k8s.io/v1/clusterrolebindings
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: rbac.authorization.k8s.io/v1/clusterroles
      namespaces:
        ignore:
        - null
        include:
        - all
    settings:
      clustername: not-configured
      configwatcher: true
      kubectl:
        commands:
          resources:
          - deployments
          - pods
          - namespaces
          - daemonsets
          - statefulsets
          - storageclasses
          - nodes
          verbs:
          - api-resources
          - api-versions
          - cluster-info
          - describe
          - diff
          - explain
          - get
          - logs
          - top
          - auth
        defaultNamespace: default
        enabled: false
        restrictAccess: false
      upgradeNotifier: true
    ssl:
      enabled: false
---
# Source: botkube/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: botkube-clusterrole
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - get
    - watch
    - list
---
# Source: botkube/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: botkube-clusterrolebinding
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: botkube-clusterrole
subjects:
- kind: ServiceAccount
  name: botkube-sa
  namespace: default
---
# Source: botkube/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: botkube
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
    component: controller
    app: botkube
spec:
  replicas: 1
  selector:
    matchLabels:
      component: controller
      app: botkube
  template:
    metadata:
      labels:
        component: controller
        app: botkube
      annotations:
        checksum/config: d2d55e6497f3096e662d5b13373c7e2b66fd8269793fbe27c9848be31a5dd0a7
    spec:
      serviceAccountName: botkube-sa
      containers:
        - name: botkube
          image: "ghcr.io/infracloudio/botkube:v0.12.3"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          
          volumeMounts:
            - name: config-volume
              mountPath: "/config"
            - name: kubeconfig
              mountPath: "/.kube"
          
          env:
            - name: CONFIG_PATH
              value: "/config/"
            - name: LOG_LEVEL
              value: "info"
            - name: METRICS_PORT
              value: "2112"
            - name: KUBECONFIG
              value: "/.kube/config"
      volumes:
        - name: config-volume
          projected:
            sources:
            - configMap:
                name: botkube-configmap
            - secret:
                name: botkube-communication-secret
        - name: kubeconfig
          secret:
            secretName: kubeconfig-supersecret
      
      securityContext:
        runAsUser: 101
        runAsGroup: 101
```

**Comment by sudermanjr** [comment]
```
helm install --debug --dry-run  botkube ./ --set kubeconfig.enabled=true --set kubeconfig.base64Config=VEhJUyBJUyBBIEtVQkVDT05GSUc= | tee /tmp/output.txt

NAME: botkube
LAST DEPLOYED: Wed Nov 24 10:53:18 2021
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
kubeconfig:
  base64Config: VEhJUyBJUyBBIEtVQkVDT05GSUc=
  enabled: true

COMPUTED VALUES:
affinity: {}
automountServiceAccountToken: true
communications:
  discord:
    botid: DISCORD_BOT_ID
    channel: DISCORD_CHANNEL_ID
    enabled: false
    notiftype: short
    token: DISCORD_TOKEN
  elasticsearch:
    awsSigning:
      awsRegion: us-east-1
      enabled: false
      roleArn: ""
    enabled: false
    index:
      name: botkube
      replicas: 0
      shards: 1
      type: botkube-event
    password: ELASTICSEARCH_PASSWORD
    server: ELASTICSEARCH_ADDRESS
    skipTLSVerify: false
    username: ELASTICSEARCH_USERNAME
  existingSecretName: ""
  mattermost:
    botName: BotKube
    channel: MATTERMOST_CHANNEL
    enabled: false
    notiftype: short
    team: MATTERMOST_TEAM
    token: MATTERMOST_TOKEN
    url: MATTERMOST_SERVER_URL
  slack:
    channel: SLACK_CHANNEL
    enabled: false
    notiftype: short
    token: SLACK_API_TOKEN
  teams:
    appID: APPLICATION_ID
    appPassword: APPLICATION_PASSWORD
    enabled: false
    notiftype: short
    port: 3978
  webhook:
    enabled: false
    url: WEBHOOK_URL
config:
  recommendations: true
  resources:
  - events:
    - create
    - delete
    - error
    name: v1/pods
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: v1/services
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - update
    - delete
    - error
    name: apps/v1/deployments
    namespaces:
      ignore:
      - null
      include:
      - all
    updateSetting:
      fields:
      - spec.template.spec.containers[*].image
      - status.availableReplicas
      includeDiff: true
  - events:
    - create
    - update
    - delete
    - error
    name: apps/v1/statefulsets
    namespaces:
      ignore:
      - null
      include:
      - all
    updateSetting:
      fields:
      - spec.template.spec.containers[*].image
      - status.readyReplicas
      includeDiff: true
  - events:
    - create
    - delete
    - error
    name: networking.k8s.io/v1beta1/ingresses
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: v1/nodes
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: v1/namespaces
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: v1/persistentvolumes
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: v1/persistentvolumeclaims
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: v1/configmaps
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - update
    - delete
    - error
    name: apps/v1/daemonsets
    namespaces:
      ignore:
      - null
      include:
      - all
    updateSetting:
      fields:
      - spec.template.spec.containers[*].image
      - status.numberReady
      includeDiff: true
  - events:
    - create
    - update
    - delete
    - error
    name: batch/v1/jobs
    namespaces:
      ignore:
      - null
      include:
      - all
    updateSetting:
      fields:
      - spec.template.spec.containers[*].image
      - status.conditions[*].type
      includeDiff: true
  - events:
    - create
    - delete
    - error
    name: rbac.authorization.k8s.io/v1/roles
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: rbac.authorization.k8s.io/v1/rolebindings
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: rbac.authorization.k8s.io/v1/clusterrolebindings
    namespaces:
      ignore:
      - null
      include:
      - all
  - events:
    - create
    - delete
    - error
    name: rbac.authorization.k8s.io/v1/clusterroles
    namespaces:
      ignore:
      - null
      include:
      - all
  settings:
    clustername: not-configured
    configwatcher: true
    kubectl:
      commands:
        resources:
        - deployments
        - pods
        - namespaces
        - daemonsets
        - statefulsets
        - storageclasses
        - nodes
        verbs:
        - api-resources
        - api-versions
        - cluster-info
        - describe
        - diff
        - explain
        - get
        - logs
        - top
        - auth
      defaultNamespace: default
      enabled: false
      restrictAccess: false
    upgradeNotifier: true
  ssl:
    enabled: false
containerSecurityContext:
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
extraAnnotations: {}
extraEnv: null
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  registry: ghcr.io
  repository: infracloudio/botkube
  tag: v0.12.3
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  create: false
  host: HOST
  tls:
    enabled: false
    secretName: ""
  urlPath: /
kubeconfig:
  base64Config: VEhJUyBJUyBBIEtVQkVDT05GSUc=
  enabled: true
  existingSecret: ""
logLevel: info
nameOverride: ""
nodeSelector: {}
podSecurityPolicy:
  enabled: false
priorityClassName: ""
rbac:
  create: true
  rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - get
    - watch
    - list
replicaCount: 1
resources: {}
securityContext:
  runAsGroup: 101
  runAsUser: 101
service:
  name: metrics
  port: 2112
  targetPort: 2112
serviceAccount:
  annotations: {}
  create: true
serviceMonitor:
  enabled: false
  interval: 10s
  labels: {}
  path: /metrics
  port: metrics
tolerations: []

HOOKS:
MANIFEST:
---
# Source: botkube/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: botkube-sa
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: botkube/templates/communicationsecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: botkube-communication-secret
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
stringData:
  comm_config.yaml: |
    # Communication settings
    communications:
      discord:
        botid: DISCORD_BOT_ID
        channel: DISCORD_CHANNEL_ID
        enabled: false
        notiftype: short
        token: DISCORD_TOKEN
      elasticsearch:
        awsSigning:
          awsRegion: us-east-1
          enabled: false
          roleArn: ""
        enabled: false
        index:
          name: botkube
          replicas: 0
          shards: 1
          type: botkube-event
        password: ELASTICSEARCH_PASSWORD
        server: ELASTICSEARCH_ADDRESS
        skipTLSVerify: false
        username: ELASTICSEARCH_USERNAME
      existingSecretName: ""
      mattermost:
        botName: BotKube
        channel: MATTERMOST_CHANNEL
        enabled: false
        notiftype: short
        team: MATTERMOST_TEAM
        token: MATTERMOST_TOKEN
        url: MATTERMOST_SERVER_URL
      slack:
        channel: SLACK_CHANNEL
        enabled: false
        notiftype: short
        token: SLACK_API_TOKEN
      teams:
        appID: APPLICATION_ID
        appPassword: APPLICATION_PASSWORD
        enabled: false
        notiftype: short
        port: 3978
      webhook:
        enabled: false
        url: WEBHOOK_URL
---
# Source: botkube/templates/kubeconfig.yaml
apiVersion: v1
kind: Secret
metadata:
  name: botkube-kubeconfig
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
data:
  config: VEhJUyBJUyBBIEtVQkVDT05GSUc=
---
# Source: botkube/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: botkube-configmap
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
data:
  resource_config.yaml: |
    recommendations: true
    resources:
    - events:
      - create
      - delete
      - error
      name: v1/pods
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: v1/services
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - update
      - delete
      - error
      name: apps/v1/deployments
      namespaces:
        ignore:
        - null
        include:
        - all
      updateSetting:
        fields:
        - spec.template.spec.containers[*].image
        - status.availableReplicas
        includeDiff: true
    - events:
      - create
      - update
      - delete
      - error
      name: apps/v1/statefulsets
      namespaces:
        ignore:
        - null
        include:
        - all
      updateSetting:
        fields:
        - spec.template.spec.containers[*].image
        - status.readyReplicas
        includeDiff: true
    - events:
      - create
      - delete
      - error
      name: networking.k8s.io/v1beta1/ingresses
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: v1/nodes
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: v1/namespaces
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: v1/persistentvolumes
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: v1/persistentvolumeclaims
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: v1/configmaps
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - update
      - delete
      - error
      name: apps/v1/daemonsets
      namespaces:
        ignore:
        - null
        include:
        - all
      updateSetting:
        fields:
        - spec.template.spec.containers[*].image
        - status.numberReady
        includeDiff: true
    - events:
      - create
      - update
      - delete
      - error
      name: batch/v1/jobs
      namespaces:
        ignore:
        - null
        include:
        - all
      updateSetting:
        fields:
        - spec.template.spec.containers[*].image
        - status.conditions[*].type
        includeDiff: true
    - events:
      - create
      - delete
      - error
      name: rbac.authorization.k8s.io/v1/roles
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: rbac.authorization.k8s.io/v1/rolebindings
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: rbac.authorization.k8s.io/v1/clusterrolebindings
      namespaces:
        ignore:
        - null
        include:
        - all
    - events:
      - create
      - delete
      - error
      name: rbac.authorization.k8s.io/v1/clusterroles
      namespaces:
        ignore:
        - null
        include:
        - all
    settings:
      clustername: not-configured
      configwatcher: true
      kubectl:
        commands:
          resources:
          - deployments
          - pods
          - namespaces
          - daemonsets
          - statefulsets
          - storageclasses
          - nodes
          verbs:
          - api-resources
          - api-versions
          - cluster-info
          - describe
          - diff
          - explain
          - get
          - logs
          - top
          - auth
        defaultNamespace: default
        enabled: false
        restrictAccess: false
      upgradeNotifier: true
    ssl:
      enabled: false
---
# Source: botkube/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: botkube-clusterrole
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - get
    - watch
    - list
---
# Source: botkube/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: botkube-clusterrolebinding
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: botkube-clusterrole
subjects:
- kind: ServiceAccount
  name: botkube-sa
  namespace: default
---
# Source: botkube/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: botkube
  labels:
    app.kubernetes.io/name: botkube
    helm.sh/chart: botkube-v0.12.3
    app.kubernetes.io/instance: botkube
    app.kubernetes.io/managed-by: Helm
    component: controller
    app: botkube
spec:
  replicas: 1
  selector:
    matchLabels:
      component: controller
      app: botkube
  template:
    metadata:
      labels:
        component: controller
        app: botkube
      annotations:
        checksum/config: d2d55e6497f3096e662d5b13373c7e2b66fd8269793fbe27c9848be31a5dd0a7
    spec:
      serviceAccountName: botkube-sa
      containers:
        - name: botkube
          image: "ghcr.io/infracloudio/botkube:v0.12.3"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
          
          volumeMounts:
            - name: config-volume
              mountPath: "/config"
            - name: kubeconfig
              mountPath: "/.kube"
          
          env:
            - name: CONFIG_PATH
              value: "/config/"
            - name: LOG_LEVEL
              value: "info"
            - name: METRICS_PORT
              value: "2112"
            - name: KUBECONFIG
              value: "/.kube/config"
      volumes:
        - name: config-volume
          projected:
            sources:
            - configMap:
                name: botkube-configmap
            - secret:
                name: botkube-communication-secret
        - name: kubeconfig
          secret:
            secretName: botkube-kubeconfig
      
      securityContext:
        runAsUser: 101
        runAsGroup: 101

```

**Review by PrasadG193 — APPROVED** [review]
Looks good

**Comment by PrasadG193** [comment]
Hey @sudermanjr, the CI failure is blocking the merge. Could you please take a look?

**Comment by sudermanjr** [comment]
@PrasadG193 the Build is failing on a go mod issue, which definitely has nothing to do with the chart. Not sure how to help here

**Comment by PrasadG193** [comment]
@sudermanjr I've fixed the issue in develop, could you please rebase your PR?

**Comment by sudermanjr** [comment]
done

**Pull request merged**
