### PR TITLE
Add support to manage filters with @BotKube command

### LINKED ISSUE #71: Capability to disable specific filters
**Is your feature request related to a problem? Please describe.**
There should be a way to enable/disable running of particular filters.

**Describe the solution you'd like**
I configuration file, we should be able specify the list of filters we want to run

### PR DESCRIPTION
**Pull request by PrasadG193**
fixes #71 

Usage:
```
@BotKube filters list : list all filters
@Botkube filters disable <filter-name> : Disable perticular filter
@Botkube filters enable <filter-name> : Enable a filter
```
Next action items:
- Update steps to create custom filter in botkube-docs
- Update BotKube help with filter command documentation

### CODE REVIEW

**Comment by PrasadG193** [comment]
Fixes: https://github.com/infracloudio/botkube/issues/71

**Comment by bhavin192** [comment]
> Fixes: #71

Please follow the Pull Request template. Adding this to PR body will close the issue when this PR is merged.

**Comment by PrasadG193** [comment]
>  PrasadG193 changed the base branch from master to develop 6 days ago
I had raised PR against master and then changed base to develop, I think that's why it didn't provide me PR template

**Comment by bhavin192** [comment]
> I had raised PR against master and then changed base to develop, I think that's why it didn't provide me PR template

Ah! no issues, we can just add fixes #num in the PR body for now, that will take care of closing the related issue ;)

**Comment by PrasadG193** [comment]
Raised PR to update documentation: https://github.com/infracloudio/botkube-docs/pull/22

**Pull request merged**
