### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by snehalbiju12**
Inserting 'the' before required in line 15

##### ISSUE TYPE

 - Feature Pull Request
 - Bug fix Pull Request
 - Docs Pull Request

##### SUMMARY

Fixes #XXX

### CODE REVIEW

**Comment by PrasadG193** [comment]
@snehalbiju12 could you please combine this with https://github.com/infracloudio/botkube/pull/381/files and address all in single PR?

**Comment by snehalbiju12** [comment]
Sure sir

**Comment by bhavin192** [comment]
This was combined with #381 and proposed as #391

**Comment by snehalbiju12** [comment]
Am i eligible for the swag?

**Pull request closed without merging**
